### PR TITLE
Feature/readme

### PR DESCRIPTION
**Pull request by JRIV-10**
ReadMe is updated to complete all the deliverables in iteration 1! Please let me know if there is anything i should change or add!

### CODE REVIEW

**Comment by mel-langhoff** [comment]
Looks good, joey! Thanks for putting this together :)

**Review by mel-langhoff — APPROVED** [review]
Looks good, thanks for doing this

**Review by readykgo — COMMENTED** [review]
looks good, thank you

**Comment by hoadam** [comment]
Thank you for your work!

**Pull request merged**
